
version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///./data/paystubs.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_TEXT=gpt-4o-mini
      - MODEL_VISION=gpt-4o-mini
      - MAX_COST_CENTS=200
    volumes:
      - ./data:/app/data

